# Generated by Django 2.1 on 2018-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='celebrity',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog/static/'),
        ),
        migrations.DeleteModel(
            name='Celebrity',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
